[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Python_cookbook"
authors = [{name = "Python_C0de", email = "python_code@qq.com"}]
dynamic = ["version", "description"]
